export {default as Jumbotron} from './jumbotron';
export {default as Footer} from './Footer';
export {default as FAQs} from './FAQs';
export {default as OptingForm} from './OptForm';
export {default as Header} from './Header';
export {default as Feature} from './Feature';
export {default as Login_Form } from './Login_form';
export {default as PaymentComp } from './Payment';
export {default as PHeader} from './payment_header';
export {default as Profiles} from './profiles';
export {default as Loading} from './Loading';
export {default as Card} from './movieCard'; 